// Copyright (c) 2026 Glenn Watson and Contributors. All rights reserved.
// Glenn Watson and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

namespace NuStreamDocs.Icons.MaterialDesign;

/// <summary>
/// Static front door for the generated MDI icon catalogue. Routes
/// every lookup through <c>MdiIconData</c> — a bucket-by-length
/// switch over the upstream Templarian/MaterialDesign-SVG set,
/// regenerated by <c>tools/NuStreamDocs.Icons.MaterialDesign.Regen</c>
/// on each MDI release.
/// </summary>
/// <remarks>
/// Lookup characteristics:
/// <list type="bullet">
/// <item>Zero startup cost — the catalogue is JIT-resolved into <c>"..."u8</c> literals on first reference. No resource decode, no dictionary build.</item>
/// <item>~50–100 ns per lookup — outer length-switch becomes a jump table, inner per-length partial is a tight chain of <c>SequenceEqual</c> compares.</item>
/// <item>Zero managed heap retention — each glyph SVG lives in the assembly's <c>#Blob</c> heap, no <c>byte[]</c> instance created.</item>
/// </list>
/// </remarks>
public static class MdiIconBundle
{
    /// <summary>Gets the number of icons in the generated catalogue.</summary>
    public static int Count => MdiIconData.Count;

    /// <summary>Tries to resolve <paramref name="name"/> to its UTF-8 SVG bytes against the generated catalogue.</summary>
    /// <param name="name">UTF-8 icon name (no <c>material-</c> prefix, no surrounding colons).</param>
    /// <param name="svg">UTF-8 SVG bytes on hit.</param>
    /// <returns>True when the icon is in the catalogue.</returns>
    public static bool TryGet(ReadOnlySpan<byte> name, out ReadOnlySpan<byte> svg) =>
        MdiIconData.TryGet(name, out svg);
}
