// Copyright (c) 2026 Glenn Watson and Contributors. All rights reserved.
// Glenn Watson and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using NuStreamDocs.Common;

namespace NuStreamDocs.Emoji;

/// <summary>Built-in shortcode-to-UTF-8-glyph table covering the high-frequency Twemoji subset. Unknown shortcodes return an empty span.</summary>
internal static class EmojiIndex
{
    /// <summary>Shortcode-to-glyph entries (lowercase ASCII shortcodes, UTF-8 glyph bytes); the first entry for a shortcode wins.</summary>
    private static readonly (byte[] Code, byte[] Glyph)[] EmojiEntries =
    [

        // Smileys.
        ([.. "smile"u8], [.. "😄"u8]),
        ([.. "smiley"u8], [.. "😃"u8]),
        ([.. "grin"u8], [.. "😁"u8]),
        ([.. "grinning"u8], [.. "😀"u8]),
        ([.. "joy"u8], [.. "😂"u8]),
        ([.. "rofl"u8], [.. "🤣"u8]),
        ([.. "wink"u8], [.. "😉"u8]),
        ([.. "blush"u8], [.. "😊"u8]),
        ([.. "heart_eyes"u8], [.. "😍"u8]),
        ([.. "kissing_heart"u8], [.. "😘"u8]),
        ([.. "kissing"u8], [.. "😗"u8]),
        ([.. "yum"u8], [.. "😋"u8]),
        ([.. "stuck_out_tongue"u8], [.. "😛"u8]),
        ([.. "stuck_out_tongue_winking_eye"u8], [.. "😜"u8]),
        ([.. "zany_face"u8], [.. "🤪"u8]),
        ([.. "face_with_raised_eyebrow"u8], [.. "🤨"u8]),
        ([.. "monocle_face"u8], [.. "🧐"u8]),
        ([.. "nerd_face"u8], [.. "🤓"u8]),
        ([.. "sunglasses"u8], [.. "😎"u8]),
        ([.. "star_struck"u8], [.. "🤩"u8]),
        ([.. "partying_face"u8], [.. "🥳"u8]),
        ([.. "thinking"u8], [.. "🤔"u8]),
        ([.. "zipper_mouth_face"u8], [.. "🤐"u8]),
        ([.. "face_with_hand_over_mouth"u8], [.. "🤭"u8]),
        ([.. "shushing_face"u8], [.. "🤫"u8]),
        ([.. "lying_face"u8], [.. "🤥"u8]),
        ([.. "expressionless"u8], [.. "😑"u8]),
        ([.. "neutral_face"u8], [.. "😐"u8]),
        ([.. "no_mouth"u8], [.. "😶"u8]),
        ([.. "smirk"u8], [.. "😏"u8]),
        ([.. "unamused"u8], [.. "😒"u8]),
        ([.. "rolling_eyes"u8], [.. "🙄"u8]),
        ([.. "grimacing"u8], [.. "😬"u8]),
        ([.. "flushed"u8], [.. "😳"u8]),
        ([.. "disappointed"u8], [.. "😞"u8]),
        ([.. "worried"u8], [.. "😟"u8]),
        ([.. "confused"u8], [.. "😕"u8]),
        ([.. "slightly_frowning_face"u8], [.. "🙁"u8]),
        ([.. "persevere"u8], [.. "😣"u8]),
        ([.. "pensive"u8], [.. "😔"u8]),
        ([.. "tired_face"u8], [.. "😫"u8]),
        ([.. "weary"u8], [.. "😩"u8]),
        ([.. "yawning_face"u8], [.. "🥱"u8]),
        ([.. "triumph"u8], [.. "😤"u8]),
        ([.. "rage"u8], [.. "😡"u8]),
        ([.. "angry"u8], [.. "😠"u8]),
        ([.. "cursing_face"u8], [.. "🤬"u8]),
        ([.. "face_with_symbols_over_mouth"u8], [.. "🤬"u8]),
        ([.. "exploding_head"u8], [.. "🤯"u8]),
        ([.. "hot_face"u8], [.. "🥵"u8]),
        ([.. "cold_face"u8], [.. "🥶"u8]),
        ([.. "woozy_face"u8], [.. "🥴"u8]),
        ([.. "dizzy_face"u8], [.. "😵"u8]),
        ([.. "face_with_spiral_eyes"u8], [.. "\U0001F635\u200D\U0001F4AB"u8]),
        ([.. "nauseated_face"u8], [.. "🤢"u8]),
        ([.. "vomiting"u8], [.. "🤮"u8]),
        ([.. "sneezing_face"u8], [.. "🤧"u8]),
        ([.. "face_with_thermometer"u8], [.. "🤒"u8]),
        ([.. "mask"u8], [.. "😷"u8]),
        ([.. "sleeping"u8], [.. "😴"u8]),
        ([.. "sleepy"u8], [.. "😪"u8]),
        ([.. "sweat_smile"u8], [.. "😅"u8]),
        ([.. "sweat"u8], [.. "😓"u8]),
        ([.. "cold_sweat"u8], [.. "😰"u8]),
        ([.. "cry"u8], [.. "😢"u8]),
        ([.. "sob"u8], [.. "😭"u8]),
        ([.. "scream"u8], [.. "😱"u8]),
        ([.. "fearful"u8], [.. "😨"u8]),
        ([.. "anguished"u8], [.. "😧"u8]),
        ([.. "hushed"u8], [.. "😯"u8]),
        ([.. "astonished"u8], [.. "😲"u8]),
        ([.. "open_mouth"u8], [.. "😮"u8]),
        ([.. "face_with_monocle"u8], [.. "🧐"u8]),
        ([.. "upside_down_face"u8], [.. "🙃"u8]),
        ([.. "relieved"u8], [.. "😌"u8]),
        ([.. "smiling_face_with_tear"u8], [.. "🥲"u8]),
        ([.. "pleading_face"u8], [.. "🥺"u8]),
        ([.. "smiling_imp"u8], [.. "😈"u8]),
        ([.. "imp"u8], [.. "👿"u8]),
        ([.. "japanese_ogre"u8], [.. "👹"u8]),
        ([.. "ghost"u8], [.. "👻"u8]),
        ([.. "skull"u8], [.. "💀"u8]),
        ([.. "skull_and_crossbones"u8], [.. "☠️"u8]),
        ([.. "alien"u8], [.. "👽"u8]),
        ([.. "space_invader"u8], [.. "👾"u8]),
        ([.. "robot"u8], [.. "🤖"u8]),
        ([.. "poop"u8], [.. "💩"u8]),

        // Hands and body.
        ([.. "thumbsup"u8], [.. "👍"u8]),
        ([.. "+1"u8], [.. "👍"u8]),
        ([.. "thumbsdown"u8], [.. "👎"u8]),
        ([.. "-1"u8], [.. "👎"u8]),
        ([.. "ok_hand"u8], [.. "👌"u8]),
        ([.. "pinching_hand"u8], [.. "🤏"u8]),
        ([.. "victory"u8], [.. "✌️"u8]),
        ([.. "crossed_fingers"u8], [.. "🤞"u8]),
        ([.. "love_you_gesture"u8], [.. "🤟"u8]),
        ([.. "metal"u8], [.. "🤘"u8]),
        ([.. "call_me_hand"u8], [.. "🤙"u8]),
        ([.. "point_left"u8], [.. "👈"u8]),
        ([.. "point_right"u8], [.. "👉"u8]),
        ([.. "point_up"u8], [.. "👆"u8]),
        ([.. "point_down"u8], [.. "👇"u8]),
        ([.. "middle_finger"u8], [.. "🖕"u8]),
        ([.. "raised_hand"u8], [.. "✋"u8]),
        ([.. "vulcan_salute"u8], [.. "🖖"u8]),
        ([.. "wave"u8], [.. "👋"u8]),
        ([.. "clap"u8], [.. "👏"u8]),
        ([.. "raised_hands"u8], [.. "🙌"u8]),
        ([.. "open_hands"u8], [.. "👐"u8]),
        ([.. "handshake"u8], [.. "🤝"u8]),
        ([.. "pray"u8], [.. "🙏"u8]),
        ([.. "muscle"u8], [.. "💪"u8]),
        ([.. "eyes"u8], [.. "👀"u8]),
        ([.. "eye"u8], [.. "👁️"u8]),
        ([.. "ear"u8], [.. "👂"u8]),
        ([.. "nose"u8], [.. "👃"u8]),
        ([.. "brain"u8], [.. "🧠"u8]),
        ([.. "see_no_evil"u8], [.. "🙈"u8]),
        ([.. "hear_no_evil"u8], [.. "🙉"u8]),
        ([.. "speak_no_evil"u8], [.. "🙊"u8]),

        // Hearts and visual effects.
        ([.. "heart"u8], [.. "❤️"u8]),
        ([.. "orange_heart"u8], [.. "🧡"u8]),
        ([.. "yellow_heart"u8], [.. "💛"u8]),
        ([.. "green_heart"u8], [.. "💚"u8]),
        ([.. "blue_heart"u8], [.. "💙"u8]),
        ([.. "purple_heart"u8], [.. "💜"u8]),
        ([.. "black_heart"u8], [.. "🖤"u8]),
        ([.. "white_heart"u8], [.. "🤍"u8]),
        ([.. "brown_heart"u8], [.. "🤎"u8]),
        ([.. "broken_heart"u8], [.. "💔"u8]),
        ([.. "two_hearts"u8], [.. "💕"u8]),
        ([.. "sparkling_heart"u8], [.. "💖"u8]),
        ([.. "growing_heart"u8], [.. "💗"u8]),
        ([.. "heartpulse"u8], [.. "💓"u8]),
        ([.. "revolving_hearts"u8], [.. "💞"u8]),
        ([.. "cupid"u8], [.. "💘"u8]),
        ([.. "gift_heart"u8], [.. "💝"u8]),
        ([.. "heart_decoration"u8], [.. "💟"u8]),
        ([.. "sparkles"u8], [.. "✨"u8]),
        ([.. "fire"u8], [.. "🔥"u8]),
        ([.. "star"u8], [.. "⭐"u8]),
        ([.. "star2"u8], [.. "🌟"u8]),
        ([.. "dizzy"u8], [.. "💫"u8]),
        ([.. "100"u8], [.. "💯"u8]),
        ([.. "zzz"u8], [.. "💤"u8]),
        ([.. "boom"u8], [.. "💥"u8]),
        ([.. "collision"u8], [.. "💥"u8]),
        ([.. "anger"u8], [.. "💢"u8]),
        ([.. "droplet"u8], [.. "💧"u8]),
        ([.. "sweat_drops"u8], [.. "💦"u8]),
        ([.. "dash"u8], [.. "💨"u8]),
        ([.. "speech_balloon"u8], [.. "💬"u8]),
        ([.. "thought_balloon"u8], [.. "💭"u8]),

        // Celebration and award.
        ([.. "tada"u8], [.. "🎉"u8]),
        ([.. "confetti_ball"u8], [.. "🎊"u8]),
        ([.. "balloon"u8], [.. "🎈"u8]),
        ([.. "birthday"u8], [.. "🎂"u8]),
        ([.. "cake"u8], [.. "🍰"u8]),
        ([.. "gift"u8], [.. "🎁"u8]),
        ([.. "ribbon"u8], [.. "🎀"u8]),
        ([.. "trophy"u8], [.. "🏆"u8]),
        ([.. "medal"u8], [.. "🏅"u8]),
        ([.. "first_place_medal"u8], [.. "🥇"u8]),
        ([.. "second_place_medal"u8], [.. "🥈"u8]),
        ([.. "third_place_medal"u8], [.. "🥉"u8]),
        ([.. "rocket"u8], [.. "🚀"u8]),
        ([.. "flying_saucer"u8], [.. "🛸"u8]),
        ([.. "crown"u8], [.. "👑"u8]),

        // Status and annotation.
        ([.. "warning"u8], [.. "⚠️"u8]),
        ([.. "white_check_mark"u8], [.. "✅"u8]),
        ([.. "heavy_check_mark"u8], [.. "✔️"u8]),
        ([.. "ballot_box_with_check"u8], [.. "☑️"u8]),
        ([.. "x"u8], [.. "❌"u8]),
        ([.. "heavy_multiplication_x"u8], [.. "✖️"u8]),
        ([.. "negative_squared_cross_mark"u8], [.. "❎"u8]),
        ([.. "bangbang"u8], [.. "‼️"u8]),
        ([.. "interrobang"u8], [.. "⁉️"u8]),
        ([.. "question"u8], [.. "❓"u8]),
        ([.. "grey_question"u8], [.. "❔"u8]),
        ([.. "exclamation"u8], [.. "❗"u8]),
        ([.. "grey_exclamation"u8], [.. "❕"u8]),
        ([.. "bulb"u8], [.. "💡"u8]),
        ([.. "information_source"u8], [.. "ℹ️"u8]),
        ([.. "rotating_light"u8], [.. "🚨"u8]),
        ([.. "no_entry"u8], [.. "⛔"u8]),
        ([.. "no_entry_sign"u8], [.. "🚫"u8]),
        ([.. "construction"u8], [.. "🚧"u8]),
        ([.. "biohazard"u8], [.. "☣️"u8]),
        ([.. "radioactive"u8], [.. "☢️"u8]),

        // Developer and engineering.
        ([.. "bug"u8], [.. "🐛"u8]),
        ([.. "ant"u8], [.. "🐜"u8]),
        ([.. "spider"u8], [.. "🕷️"u8]),
        ([.. "wrench"u8], [.. "🔧"u8]),
        ([.. "hammer"u8], [.. "🔨"u8]),
        ([.. "hammer_and_wrench"u8], [.. "🛠️"u8]),
        ([.. "nut_and_bolt"u8], [.. "🔩"u8]),
        ([.. "gear"u8], [.. "⚙️"u8]),
        ([.. "toolbox"u8], [.. "🧰"u8]),
        ([.. "package"u8], [.. "📦"u8]),
        ([.. "computer"u8], [.. "💻"u8]),
        ([.. "desktop_computer"u8], [.. "🖥️"u8]),
        ([.. "keyboard"u8], [.. "⌨️"u8]),
        ([.. "printer"u8], [.. "🖨️"u8]),
        ([.. "trackball"u8], [.. "🖲️"u8]),
        ([.. "computer_mouse"u8], [.. "🖱️"u8]),
        ([.. "floppy_disk"u8], [.. "💾"u8]),
        ([.. "cd"u8], [.. "💿"u8]),
        ([.. "dvd"u8], [.. "📀"u8]),
        ([.. "minidisc"u8], [.. "💽"u8]),
        ([.. "battery"u8], [.. "🔋"u8]),
        ([.. "electric_plug"u8], [.. "🔌"u8]),
        ([.. "lock"u8], [.. "🔒"u8]),
        ([.. "unlock"u8], [.. "🔓"u8]),
        ([.. "lock_with_ink_pen"u8], [.. "🔏"u8]),
        ([.. "closed_lock_with_key"u8], [.. "🔐"u8]),
        ([.. "key"u8], [.. "🔑"u8]),
        ([.. "old_key"u8], [.. "🗝️"u8]),
        ([.. "mag"u8], [.. "🔍"u8]),
        ([.. "mag_right"u8], [.. "🔎"u8]),
        ([.. "memo"u8], [.. "📝"u8]),
        ([.. "pencil"u8], [.. "✏️"u8]),
        ([.. "pencil2"u8], [.. "✏️"u8]),
        ([.. "black_nib"u8], [.. "✒️"u8]),
        ([.. "paperclip"u8], [.. "📎"u8]),
        ([.. "scissors"u8], [.. "✂️"u8]),
        ([.. "books"u8], [.. "📚"u8]),
        ([.. "book"u8], [.. "📖"u8]),
        ([.. "notebook"u8], [.. "📓"u8]),
        ([.. "page_facing_up"u8], [.. "📄"u8]),
        ([.. "page_with_curl"u8], [.. "📃"u8]),
        ([.. "scroll"u8], [.. "📜"u8]),
        ([.. "clipboard"u8], [.. "📋"u8]),
        ([.. "file_folder"u8], [.. "📁"u8]),
        ([.. "open_file_folder"u8], [.. "📂"u8]),
        ([.. "card_index_dividers"u8], [.. "🗂️"u8]),
        ([.. "date"u8], [.. "📅"u8]),
        ([.. "calendar"u8], [.. "📆"u8]),
        ([.. "chart_with_upwards_trend"u8], [.. "📈"u8]),
        ([.. "chart_with_downwards_trend"u8], [.. "📉"u8]),
        ([.. "bar_chart"u8], [.. "📊"u8]),
        ([.. "link"u8], [.. "🔗"u8]),
        ([.. "paperclips"u8], [.. "🖇️"u8]),
        ([.. "pushpin"u8], [.. "📌"u8]),
        ([.. "round_pushpin"u8], [.. "📍"u8]),
        ([.. "triangular_ruler"u8], [.. "📐"u8]),
        ([.. "straight_ruler"u8], [.. "📏"u8]),
        ([.. "zap"u8], [.. "⚡"u8]),
        ([.. "recycle"u8], [.. "♻️"u8]),
        ([.. "infinity"u8], [.. "♾️"u8]),
        ([.. "hourglass"u8], [.. "⌛"u8]),
        ([.. "hourglass_flowing_sand"u8], [.. "⏳"u8]),
        ([.. "watch"u8], [.. "⌚"u8]),
        ([.. "alarm_clock"u8], [.. "⏰"u8]),
        ([.. "stopwatch"u8], [.. "⏱️"u8]),
        ([.. "timer_clock"u8], [.. "⏲️"u8]),
        ([.. "test_tube"u8], [.. "🧪"u8]),
        ([.. "petri_dish"u8], [.. "🧫"u8]),
        ([.. "dna"u8], [.. "🧬"u8]),
        ([.. "microscope"u8], [.. "🔬"u8]),
        ([.. "telescope"u8], [.. "🔭"u8]),
        ([.. "satellite"u8], [.. "🛰️"u8]),
        ([.. "magnet"u8], [.. "🧲"u8]),
        ([.. "compass"u8], [.. "🧭"u8]),
        ([.. "balance_scale"u8], [.. "⚖️"u8]),

        // Directional and process arrows.
        ([.. "arrow_up"u8], [.. "⬆️"u8]),
        ([.. "arrow_down"u8], [.. "⬇️"u8]),
        ([.. "arrow_left"u8], [.. "⬅️"u8]),
        ([.. "arrow_right"u8], [.. "➡️"u8]),
        ([.. "arrow_upper_left"u8], [.. "↖️"u8]),
        ([.. "arrow_upper_right"u8], [.. "↗️"u8]),
        ([.. "arrow_lower_left"u8], [.. "↙️"u8]),
        ([.. "arrow_lower_right"u8], [.. "↘️"u8]),
        ([.. "arrow_up_down"u8], [.. "↕️"u8]),
        ([.. "left_right_arrow"u8], [.. "↔️"u8]),
        ([.. "leftwards_arrow_with_hook"u8], [.. "↩️"u8]),
        ([.. "arrow_right_hook"u8], [.. "↪️"u8]),
        ([.. "arrow_heading_up"u8], [.. "⤴️"u8]),
        ([.. "arrow_heading_down"u8], [.. "⤵️"u8]),
        ([.. "arrows_clockwise"u8], [.. "🔃"u8]),
        ([.. "arrows_counterclockwise"u8], [.. "🔄"u8]),
        ([.. "repeat"u8], [.. "🔁"u8]),
        ([.. "repeat_one"u8], [.. "🔂"u8]),
        ([.. "twisted_rightwards_arrows"u8], [.. "🔀"u8]),

        // Weather and nature.
        ([.. "sun"u8], [.. "☀️"u8]),
        ([.. "sunny"u8], [.. "☀️"u8]),
        ([.. "partly_sunny"u8], [.. "⛅"u8]),
        ([.. "cloud"u8], [.. "☁️"u8]),
        ([.. "rainbow"u8], [.. "🌈"u8]),
        ([.. "snowflake"u8], [.. "❄️"u8]),
        ([.. "snowman"u8], [.. "⛄"u8]),
        ([.. "comet"u8], [.. "☄️"u8]),
        ([.. "crescent_moon"u8], [.. "🌙"u8]),
        ([.. "first_quarter_moon"u8], [.. "🌓"u8]),
        ([.. "full_moon"u8], [.. "🌕"u8]),
        ([.. "new_moon"u8], [.. "🌑"u8]),
        ([.. "earth_americas"u8], [.. "🌎"u8]),
        ([.. "earth_africa"u8], [.. "🌍"u8]),
        ([.. "earth_asia"u8], [.. "🌏"u8]),
        ([.. "ocean"u8], [.. "🌊"u8]),
        ([.. "evergreen_tree"u8], [.. "🌲"u8]),
        ([.. "deciduous_tree"u8], [.. "🌳"u8]),
        ([.. "palm_tree"u8], [.. "🌴"u8]),
        ([.. "cactus"u8], [.. "🌵"u8]),
        ([.. "seedling"u8], [.. "🌱"u8]),
        ([.. "herb"u8], [.. "🌿"u8]),
        ([.. "four_leaf_clover"u8], [.. "🍀"u8]),
        ([.. "leaves"u8], [.. "🍃"u8]),
        ([.. "rose"u8], [.. "🌹"u8]),
        ([.. "sunflower"u8], [.. "🌻"u8]),
        ([.. "tulip"u8], [.. "🌷"u8]),
        ([.. "hibiscus"u8], [.. "🌺"u8]),
        ([.. "blossom"u8], [.. "🌼"u8]),
        ([.. "cherry_blossom"u8], [.. "🌸"u8]),

        // Animals.
        ([.. "dog"u8], [.. "🐶"u8]),
        ([.. "cat"u8], [.. "🐱"u8]),
        ([.. "mouse"u8], [.. "🐭"u8]),
        ([.. "hamster"u8], [.. "🐹"u8]),
        ([.. "rabbit"u8], [.. "🐰"u8]),
        ([.. "fox"u8], [.. "🦊"u8]),
        ([.. "bear"u8], [.. "🐻"u8]),
        ([.. "panda"u8], [.. "🐼"u8]),
        ([.. "koala"u8], [.. "🐨"u8]),
        ([.. "tiger"u8], [.. "🐯"u8]),
        ([.. "lion"u8], [.. "🦁"u8]),
        ([.. "cow"u8], [.. "🐮"u8]),
        ([.. "pig"u8], [.. "🐷"u8]),
        ([.. "frog"u8], [.. "🐸"u8]),
        ([.. "monkey"u8], [.. "🐵"u8]),
        ([.. "chicken"u8], [.. "🐔"u8]),
        ([.. "penguin"u8], [.. "🐧"u8]),
        ([.. "bird"u8], [.. "🐦"u8]),
        ([.. "eagle"u8], [.. "🦅"u8]),
        ([.. "owl"u8], [.. "🦉"u8]),
        ([.. "duck"u8], [.. "🦆"u8]),
        ([.. "turtle"u8], [.. "🐢"u8]),
        ([.. "snake"u8], [.. "🐍"u8]),
        ([.. "octopus"u8], [.. "🐙"u8]),
        ([.. "whale"u8], [.. "🐳"u8]),
        ([.. "dolphin"u8], [.. "🐬"u8]),
        ([.. "fish"u8], [.. "🐟"u8]),
        ([.. "shark"u8], [.. "🦈"u8]),
        ([.. "crocodile"u8], [.. "🐊"u8]),
        ([.. "dragon"u8], [.. "🐉"u8]),
        ([.. "dragon_face"u8], [.. "🐲"u8]),
        ([.. "unicorn"u8], [.. "🦄"u8]),
        ([.. "horse"u8], [.. "🐴"u8]),
        ([.. "zebra"u8], [.. "🦓"u8]),
        ([.. "giraffe"u8], [.. "🦒"u8]),
        ([.. "elephant"u8], [.. "🐘"u8]),
        ([.. "butterfly"u8], [.. "🦋"u8]),
        ([.. "bee"u8], [.. "🐝"u8]),
        ([.. "snail"u8], [.. "🐌"u8]),
        ([.. "paw_prints"u8], [.. "🐾"u8]),

        // Food and drink.
        ([.. "coffee"u8], [.. "☕"u8]),
        ([.. "tea"u8], [.. "🍵"u8]),
        ([.. "beer"u8], [.. "🍺"u8]),
        ([.. "beers"u8], [.. "🍻"u8]),
        ([.. "wine_glass"u8], [.. "🍷"u8]),
        ([.. "cocktail"u8], [.. "🍸"u8]),
        ([.. "champagne"u8], [.. "🍾"u8]),
        ([.. "clinking_glasses"u8], [.. "🥂"u8]),
        ([.. "milk_glass"u8], [.. "🥛"u8]),
        ([.. "baby_bottle"u8], [.. "🍼"u8]),
        ([.. "apple"u8], [.. "🍎"u8]),
        ([.. "green_apple"u8], [.. "🍏"u8]),
        ([.. "banana"u8], [.. "🍌"u8]),
        ([.. "grapes"u8], [.. "🍇"u8]),
        ([.. "strawberry"u8], [.. "🍓"u8]),
        ([.. "watermelon"u8], [.. "🍉"u8]),
        ([.. "peach"u8], [.. "🍑"u8]),
        ([.. "cherries"u8], [.. "🍒"u8]),
        ([.. "lemon"u8], [.. "🍋"u8]),
        ([.. "pineapple"u8], [.. "🍍"u8]),
        ([.. "avocado"u8], [.. "🥑"u8]),
        ([.. "tomato"u8], [.. "🍅"u8]),
        ([.. "eggplant"u8], [.. "🍆"u8]),
        ([.. "carrot"u8], [.. "🥕"u8]),
        ([.. "corn"u8], [.. "🌽"u8]),
        ([.. "hot_pepper"u8], [.. "🌶️"u8]),
        ([.. "pizza"u8], [.. "🍕"u8]),
        ([.. "hamburger"u8], [.. "🍔"u8]),
        ([.. "hotdog"u8], [.. "🌭"u8]),
        ([.. "taco"u8], [.. "🌮"u8]),
        ([.. "burrito"u8], [.. "🌯"u8]),
        ([.. "sushi"u8], [.. "🍣"u8]),
        ([.. "ramen"u8], [.. "🍜"u8]),
        ([.. "rice_ball"u8], [.. "🍙"u8]),
        ([.. "doughnut"u8], [.. "🍩"u8]),
        ([.. "cookie"u8], [.. "🍪"u8]),
        ([.. "chocolate_bar"u8], [.. "🍫"u8]),
        ([.. "candy"u8], [.. "🍬"u8]),
        ([.. "ice_cream"u8], [.. "🍨"u8]),

        // Travel and transport.
        ([.. "car"u8], [.. "🚗"u8]),
        ([.. "taxi"u8], [.. "🚕"u8]),
        ([.. "bus"u8], [.. "🚌"u8]),
        ([.. "train"u8], [.. "🚆"u8]),
        ([.. "bullettrain_side"u8], [.. "🚄"u8]),
        ([.. "airplane"u8], [.. "✈️"u8]),
        ([.. "helicopter"u8], [.. "🚁"u8]),
        ([.. "ship"u8], [.. "🚢"u8]),
        ([.. "sailboat"u8], [.. "⛵"u8]),
        ([.. "anchor"u8], [.. "⚓"u8]),
        ([.. "bike"u8], [.. "🚲"u8]),
        ([.. "motorcycle"u8], [.. "🏍️"u8]),
        ([.. "scooter"u8], [.. "🛴"u8]),
        ([.. "traffic_light"u8], [.. "🚦"u8]),
        ([.. "vertical_traffic_light"u8], [.. "🚥"u8]),
        ([.. "fuel_pump"u8], [.. "⛽"u8]),
        ([.. "globe_with_meridians"u8], [.. "🌐"u8]),
        ([.. "world_map"u8], [.. "🗺️"u8]),

        // Music and instruments.
        ([.. "musical_note"u8], [.. "🎵"u8]),
        ([.. "notes"u8], [.. "🎶"u8]),
        ([.. "microphone"u8], [.. "🎤"u8]),
        ([.. "studio_microphone"u8], [.. "🎙️"u8]),
        ([.. "headphones"u8], [.. "🎧"u8]),
        ([.. "guitar"u8], [.. "🎸"u8]),
        ([.. "musical_keyboard"u8], [.. "🎹"u8]),
        ([.. "trumpet"u8], [.. "🎺"u8]),
        ([.. "violin"u8], [.. "🎻"u8]),
        ([.. "drum"u8], [.. "🥁"u8]),

        // Sports.
        ([.. "soccer"u8], [.. "⚽"u8]),
        ([.. "basketball"u8], [.. "🏀"u8]),
        ([.. "football"u8], [.. "🏈"u8]),
        ([.. "baseball"u8], [.. "⚾"u8]),
        ([.. "tennis"u8], [.. "🎾"u8]),
        ([.. "volleyball"u8], [.. "🏐"u8]),
        ([.. "rugby_football"u8], [.. "🏉"u8]),
        ([.. "8ball"u8], [.. "🎱"u8]),
        ([.. "dart"u8], [.. "🎯"u8]),
        ([.. "bowling"u8], [.. "🎳"u8]),
        ([.. "ping_pong"u8], [.. "🏓"u8]),
        ([.. "badminton"u8], [.. "🏸"u8]),
    ];

    /// <summary>Shortcode-to-glyph lookup built once from <see cref="EmojiEntries"/>.</summary>
    private static readonly Dictionary<byte[], byte[]> GlyphsByShortcode = BuildTable();

    /// <summary>Tries to resolve <paramref name="shortcode"/> to a glyph.</summary>
    /// <param name="shortcode">UTF-8 shortcode bytes (without surrounding colons).</param>
    /// <param name="glyph">Resolved glyph bytes on success.</param>
    /// <returns>True when the shortcode is known.</returns>
    public static bool TryGet(ReadOnlySpan<byte> shortcode, out ReadOnlySpan<byte> glyph)
    {
        glyph = MatchGlyph(shortcode);
        return glyph.Length > 0;
    }

    /// <summary>Matches <paramref name="shortcode"/> against the curated table.</summary>
    /// <param name="shortcode">UTF-8 shortcode bytes.</param>
    /// <returns>Glyph bytes on match, or an empty span on miss.</returns>
    private static ReadOnlySpan<byte> MatchGlyph(ReadOnlySpan<byte> shortcode) =>
        GlyphsByShortcode.GetAlternateLookup<ReadOnlySpan<byte>>().TryGetValue(shortcode, out var glyph) ? glyph : default;

    /// <summary>Builds the shortcode-to-glyph lookup, keeping the first entry when a shortcode repeats.</summary>
    /// <returns>The populated table.</returns>
    private static Dictionary<byte[], byte[]> BuildTable()
    {
        Dictionary<byte[], byte[]> table = new(EmojiEntries.Length, ByteArrayComparer.Instance);
        for (var i = 0; i < EmojiEntries.Length; i++)
        {
            table.TryAdd(EmojiEntries[i].Code, EmojiEntries[i].Glyph);
        }

        return table;
    }
}
