<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <RootNamespace>NuStreamDocs.Serve.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NuStreamDocs.Serve\NuStreamDocs.Serve.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging"/>
  </ItemGroup>

</Project>
