// Copyright (c) 2026 Glenn Watson and Contributors. All rights reserved.
// Glenn Watson and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Text;

namespace NuStreamDocs.ParityCheck.Tests;

/// <summary>Generates the source of the pinned-output tests from the sidecars of the corpus.</summary>
internal static class PinnedRowEmitter
{
    /// <summary>Initial capacity of the source builder, in characters.</summary>
    private const int SourceCapacity = 65_536;

    /// <summary>Generates the test class source.</summary>
    /// <param name="fragments">The whole corpus.</param>
    /// <returns>The source text and the number of rows it holds.</returns>
    /// <exception cref="InvalidOperationException">A fragment without pinned HTML failed to render.</exception>
    internal static PinnedRowSource Emit(Fragment[] fragments)
    {
        var builder = new StringBuilder(SourceCapacity);
        AppendHeader(builder);
        var rows = 0;
        for (var k = 0; k < ExpectationKinds.Pinned.Length; k++)
        {
            _ = builder.Append(k is 0 ? string.Empty : "\n");
            rows += AppendMethod(builder, ExpectationKinds.Pinned[k], fragments);
        }

        _ = builder.Append("}\n");
        return new(builder.ToString(), rows);
    }

    /// <summary>Appends the file header and the class declaration.</summary>
    /// <param name="builder">Destination.</param>
    private static void AppendHeader(StringBuilder builder) =>
        _ = builder.Append("// Copyright (c) 2026 Glenn Watson and Contributors. All rights reserved.\n")
            .Append("// Glenn Watson and Contributors licenses this file to you under the MIT license.\n")
            .Append("// See the LICENSE file in the project root for full license information.\n")
            .Append("// <auto-generated>\n")
            .Append("// Generated from the fragment sidecars by 'dotnet run --file tools/Program.cs -- --emit-pinned'. Edits are overwritten.\n")
            .Append("// </auto-generated>\n")
            .Append("namespace NuStreamDocs.ParityCheck.Tests;\n\n")
            .Append("/// <summary>Renders the fragments whose sidecars pin deliberate behavior and asserts the pinned HTML. Needs no reference engine.</summary>\n")
            .Append("public sealed class ").Append(PinnedOutputNames.ClassName).Append('\n')
            .Append("{\n");

    /// <summary>Appends the test method for one sidecar kind with a row per fragment of that kind.</summary>
    /// <param name="builder">Destination.</param>
    /// <param name="kind">Sidecar kind.</param>
    /// <param name="fragments">The whole corpus.</param>
    /// <returns>The number of rows appended.</returns>
    private static int AppendMethod(StringBuilder builder, string kind, Fragment[] fragments)
    {
        _ = builder.Append("    /// <summary>Rendering the fragment produces the HTML pinned by its ").Append(kind).Append(" sidecar.</summary>\n")
            .Append("    /// <param name=\"markdown\">Markdown source of the fragment.</param>\n")
            .Append("    /// <param name=\"expectedHtml\">Pinned HTML.</param>\n")
            .Append("    /// <returns>The assertion task.</returns>\n")
            .Append("    [Test]\n");

        var rows = 0;
        foreach (var fragment in fragments)
        {
            if (fragment.Expect is not { } expectation || expectation.Kind != kind)
            {
                continue;
            }

            _ = builder.Append("    [Arguments(")
                .Append(CSharpLiteral.Quote(fragment.Markdown)).Append(", ")
                .Append(CSharpLiteral.Quote(expectation.PinnedHtml ?? OursHtml(fragment))).Append(", DisplayName = ")
                .Append(CSharpLiteral.Quote(PinnedOutputNames.DisplayName(fragment.Id, expectation))).Append(")]\n");
            rows++;
        }

        _ = builder.Append("    public async Task ").Append(PinnedOutputNames.MethodName(kind)).Append("(string markdown, string expectedHtml)\n")
            .Append("    {\n")
            .Append("        await PinnedOutputAssertion.RendersAsync(markdown, expectedHtml);\n")
            .Append("    }\n");
        return rows;
    }

    /// <summary>Renders a fragment with our renderer for a sidecar that carries no pinned HTML.</summary>
    /// <param name="fragment">The fragment.</param>
    /// <returns>Our HTML.</returns>
    /// <exception cref="InvalidOperationException">The fragment failed to render.</exception>
    private static string OursHtml(Fragment fragment)
    {
        var rendered = OursRenderer.Render(fragment.Markdown);
        return rendered.Html ?? throw new InvalidOperationException($"'{fragment.Id}' failed to render: {rendered.Error}");
    }
}
